### ISSUE TITLE
JSON field support

### ISSUE THREAD

**Issue by ranjanse** [nreco/csv#5]
File contains 3 columns: 
AddressId, JsonData, UpdatedAt
1,"{\"address\": {\"zip\": null, \"city\": null, \"state\": null, \"country\": \"USA\", \"street1\": null, \"street2\": null, \"street3\": null}}","2021-03-31T23:36:04"
2,"{\"guardian\": {\"name\": \"Abhishek\", \"phone\": true, \"address\": {\"zip\": \"6204\", \"city\": \"York\", \"state\": \"PA\", \"country\": \"USA\", \"street1\": \"62115B Greenwood Rd\", \"street2\": null, \"street3\": null}, \"relationship\": \"Son\"}}","2021-03-31T23:36:04"

![image](https://user-images.githubusercontent.com/24838421/127447126-f19060f9-7c9a-496d-b6b4-8882466a23af.png)

I am not able to find "UpdatedAt" field at csvReader[2]. Please add json support also. thanks

**Comment by VitaliyMF** [comment]
In CSV (https://datatracker.ietf.org/doc/html/rfc4180) double-quotes that are part of the column's value should be escaped in this way:  " -> ""

>   7.  If double-quotes are used to enclose fields, then a double-quote
>       appearing inside a field must be escaped by preceding it with
>       another double quote.  For example:
>
>     "aaa","b""bb","ccc"

**Comment by ranjanse** [comment]
Ok. Thanks for your quick reply.
Any work around for this non-standard file? 

Please see if it is possible to handle such file also otherwise you can close this thread.

**Comment by VitaliyMF** [comment]
> Any work around for this non-standard file?

pre-process input data (say, with custom Stream-wrapper class) and replace \" to "".
