### ISSUE TITLE
[Question] Does NReco.Csv write fully-correct CSV files?

### ISSUE THREAD

**Issue by SpiritBob** [nreco/csv#8]
It seems the library is capable of reading not fully correct CSV files. if you can expand on the differences, as I'm guessing your model is specified in [RFC4180](https://www.rfc-editor.org/rfc/rfc4180)? 

With that said, does the library itself produce CSV files conforming to the above RFC standard?

**Comment by VitaliyMF** [comment]
> if you can expand on the differences, as I'm guessing your model is specified in [RFC4180](https://www.rfc-editor.org/rfc/rfc4180)?

CSV reader code is rather simple: https://github.com/nreco/csv/blob/master/src/NReco.Csv/CsvReader.cs
In short, it can be used to read CSVs where lines contain different number of columns, or if there are no closing " (of the value in quotes).

> With that said, does the library itself produce CSV files conforming to the above RFC standard?

CSV writer produces correct output according to the RFC.
